"""init

Revision ID: 2b6e30724a5d
Revises: 5eadb1ef8850
Create Date: 2026-01-25 14:03:47.057295
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2b6e30724a5d'
down_revision = '5eadb1ef8850'
branch_labels = None
depends_on = None


def upgrade():
  # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
  # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
